spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_test
    driver-class-name: org.postgresql.Driver
    username: matvey
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
